//@version=6
indicator("TGK CDC Lookalike Account 2", overlay=true)

//==================================================
// INPUT
//==================================================

emaFastLen = input.int(12, "EMA Fast")
emaSlowLen = input.int(26, "EMA Slow")

showDebug = input.bool(true)

//==================================================
// EMA
//==================================================

ema12 = ta.ema(close, emaFastLen)
ema26 = ta.ema(close, emaSlowLen)

plot(ema12, color=color.green)
plot(ema26, color=color.orange)

//==================================================
// CROSS
//==================================================

greenCross = ta.crossover(ema12, ema26)
redCross   = ta.crossunder(ema12, ema26)

plotshape(greenCross,
     style=shape.circle,
     color=color.lime,
     size=size.small,
     location=location.belowbar)

plotshape(redCross,
     style=shape.circle,
     color=color.red,
     size=size.small,
     location=location.abovebar)

//==================================================
// CURRENT SEGMENT
//==================================================

var int segStart = na

var float currentHigh = na
var float currentLow  = na

var int currentHighBar = na
var int currentLowBar  = na

var bool currentIsGreen = ema12 > ema26

//==================================================
// HISTORY
//==================================================
type Segment
    int startBar
    int endBar

    int crossBar

    float highest
    int highestBar

    float lowest
    int lowestBar

    bool isGreen

var segments = array.new<Segment>()

//==================================================
// SEGMENT FUNCTIONS
//==================================================

HasEnoughSegments(int count) =>
    array.size(segments) >= count

GetSegment(int offset) =>
    array.get(segments, array.size(segments) - 1 - offset)

//==================================================
// Pattern Checking Functions
//==================================================
IsBuyPattern() =>
    if not HasEnoughSegments(3)
        false
    else
        Segment s0 = GetSegment(0)
        Segment s1 = GetSegment(1)
        Segment s2 = GetSegment(2)

        not s2.isGreen and s1.isGreen and not s0.isGreen

IsSellPattern() =>
    if not HasEnoughSegments(3)
        false
    else
        Segment s0 = GetSegment(0)
        Segment s1 = GetSegment(1)
        Segment s2 = GetSegment(2)

        s2.isGreen and not s1.isGreen and s0.isGreen

//==================================================
// INITIALIZE
//==================================================

if barstate.isfirst
    segStart := bar_index
    currentHigh := high
    currentLow := low
    currentHighBar := bar_index
    currentLowBar := bar_index
    currentIsGreen := ema12 > ema26

//==================================================
// UPDATE CURRENT SEGMENT
//==================================================

if high > currentHigh
    currentHigh := high
    currentHighBar := bar_index

if low < currentLow
    currentLow := low
    currentLowBar := bar_index

//==================================================
// SAVE SEGMENT
//==================================================

crossHappened = greenCross or redCross

if crossHappened
    seg = Segment.new(
        segStart,
        bar_index - 1,
        bar_index,
        currentHigh,
        currentHighBar,
        currentLow,
        currentLowBar,
        currentIsGreen
    )
    array.push(segments, seg)

    //--------------------------------------
    // Start next segment
    //--------------------------------------

    segStart := bar_index

    currentHigh := high
    currentHighBar := bar_index

    currentLow := low
    currentLowBar := bar_index

    currentIsGreen := greenCross

//==================================================
// DEBUG
//==================================================
if showDebug and crossHappened
    Segment s0 = GetSegment(0)
    string msg = ""
    float y = s0.isGreen ? s0.highest : s0.lowest

    if IsBuyPattern()
        msg := "BUY Pattern"

    if IsSellPattern()
        msg := "SELL Pattern"

    if msg != ""
        label.new(
            bar_index,
            y,
            msg,
            style= s0.isGreen ? label.style_label_down : label.style_label_up,
            color=color.blue,
            textcolor=color.white
        )
